export const userFormFieldsList = [
    {
        id: "id",
        name: "userIdentifier",
        label: "Nombre de usuario",
        type: "text",
        required: true,
        multiple: false,
    },
    {
        id: "id",
        name: "email",
        label: "Email",
        type: "text",
        required: true,
        multiple: false,
    },
    {
        id: "id",
        name: "password",
        label: "Contraseña",
        type: "password",
        required: true,
        multiple: false,
    },
    {
        id: "id",
        name: "userType",
        label: "Tipo de usuario",
        type: "select",
        required: true,
        multiple: false,
        options: ["Profesor", "Estudiante", "Administrador"],
    },
    {
        id: "id",
        name: "userRoles",
        label: "Roles de usuario",
        type: "select",
        required: true,
        multiple: true,
        options: ['Ver', 'Crear', 'Editar', 'Eliminar'],
    },
];

export const expenseTypeFormFieldsList = [
    {
        id: "id",
        name: "description",
        label: "Descripción",
        type: "text",
        required: true,
        multiple: false,
    },
    {
        id: "id",
        name: "active",
        label: "Activo",
        type: "text",
        required: true,
        multiple: false,
    },
    {
        id: "id",
        name: "created",
        label: "Fecha de creación",
        type: "checkbox",
        required: true,
        multiple: false,
    },
    {
        id: "id",
        name: "modified",
        label: "Fecha de modificación",
        type: "checkbox",
        required: true,
        multiple: false,
    },
];